const jobs = [
    {
      id: 1,
      title: 'Full-stack Developer',
      description: 'We are looking for an experienced full-stack developer to join our team.',
      technologies: ['React', 'Node.js'],
      clientName: 'ABC Company',
      clientRatings: 4.5,
      clientHires: 10,
    },
    {
      id: 2,
      title: 'Front-end Developer',
      description: 'We are seeking a talented front-end developer to work on our client-side applications.',
      technologies: ['React', 'JavaScript'],
      clientName: 'XYZ Inc.',
      clientRatings: 4.8,
      clientHires: 25,
    },
    {
      id: 3,
      title: 'Software Engineer',
      description: 'We are looking for a software engineer to design and develop high-quality software products.',
      technologies: ['Java', 'Python', 'SQL'],
      clientName: '123 Corporation',
      clientRatings: 4.2,
      clientHires: 8,
    },
    {
      id: 4,
      title: 'Back-end Developer',
      description: 'We are seeking an experienced back-end developer to join our team and help us build scalable web applications.',
      technologies: ['Node.js', 'MongoDB'],
      clientName: 'XYZ Inc.',
      clientRatings: 4.9,
      clientHires: 15,
    },
    {
      id: 5,
      title: 'Mobile App Developer',
      description: 'We are seeking a skilled mobile app developer to create and maintain mobile applications for iOS and Android devices.',
      technologies: ['React Native', 'Swift', 'Kotlin'],
      clientName: 'ABC Company',
      clientRatings: 4.7,
      clientHires: 12,
    },
    {
      id: 6,
      title: 'Data Analyst',
      description: 'We are looking for a data analyst to join our team and help us turn data into insights.',
      technologies: ['Python', 'R', 'SQL'],
      clientName: '789 Enterprises',
      clientRatings: 4.3,
      clientHires: 7,
    },
    {
      id: 7,
      title: 'Cloud Engineer',
      description: 'We are seeking a cloud engineer to help us design, build, and maintain cloud infrastructure.',
      technologies: ['AWS', 'Google Cloud Platform', 'Azure'],
      clientName: '456 Corporation',
      clientRatings: 4.6,
      clientHires: 10,
    },
    {
      id: 8,
      title: 'UI/UX Designer',
      description: 'We are looking for a talented UI/UX designer to join our team and help us create beautiful and functional user interfaces.',
      technologies: ['Adobe XD', 'Figma', 'Sketch'],
      clientName: 'XYZ Inc.',
      clientRatings: 4.8,
      clientHires: 20,
    },
    {
      id: 9,
      title: 'Quality Assurance Engineer',
      description: 'We are seeking a quality assurance engineer to help us ensure that our products meet the highest standards of quality.',
      technologies: ['Selenium', 'JMeter', 'Postman'],
      clientName: 'ABC Company',
      clientRatings: 4.4,
      clientHires: 9,
    }];

    export default jobs;