 const technologies = [
    "React",
    "Angular",
    "Vue.js",
    "JavaScript",
    "TypeScript",
    "Node.js",
    "Python",
    "Java",
    "C#",
    "PHP",
    "Ruby",
    "Swift",
    "Kotlin",
    "SQL",
    "NoSQL",
    "AWS",
    "Azure",
    "Google Cloud Platform",
    "Docker",
    "Kubernetes",
    "CI/CD",
    "Git",
    "Agile",
    "Scrum",
    "DevOps",
    "Machine Learning",
    "Data Science",
    "Big Data",
    "Cybersecurity",
    "Blockchain",
    "UI/UX Design",
    "Graphic Design",
    "Video Editing",
    "Copywriting",
    "Content Writing",
    "Social Media Management",
    "SEO",
    "SEM",
    "PPC Advertising",
    "Email Marketing",
    "Customer Service",
    "Virtual Assistance",
    "Project Management",
    "Sales",
    "Marketing",
    "Finance",
    "Accounting",
    "Human Resources",
    "Legal",
  ];


  export default technologies;
